docs_dir: /docs
site_name: CyVerse Core Software Documentation
site_url: https://cyverse.github.io/docs
site_description: CyVerse USA Documentation
site_author: 'CyVerse USA'

# uncomment to show the github icon in the header with
# number of forks & stars
repo_url: https://github.com/cyverse/docs
edit_uri: edit/main/docs

# Copyright
copyright: 'Copyright &copy; 2016-2023 CyVerse'

# logos
medunilogo: 'images/logo-meduni-graz.png'
unigrazlogo: 'images/universitaet_graz_logo_signet.png'
tugrazlogo: 'images/TUG.png'

imgwidth: 70px;
theme:
  highlightjs: true
  features:
    - navigation.tabs
  name: material
  # custom_dir: 'overrides'
  palette:
    primary: 'white'
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'images/cyverse_ball_2022.png'
  favicon: 'images/favicon.ico'


nav:
  - Home: 'index.md'
  # - Development:
  #   - overview: 'development/index.md'
  - Services:
    - Kubernetes: 'services/kubernetes/index.md'
    - KeyCloak: 'services/keycloak/realm.md'
    - Namespaces: 'services/kubernetes/ns.md'
  - Deployments:
    - Kubernetes (K8s): 'deployments/kubernetes-deploy.md'
    - User Portal: 'deployments/userportal.md'
    - OpenEBS: 'deployments/openebs.md'
    - KeyCloak: 'deployments/keycloak.md'
    - Mail: 'deployments/exim4.md'
    - Redis HA: 'deployments/redis-ha.md'
    - K8s Resources: 'deployments/k8s-resources.md'
    - ElasticSearch: 'deployments/elasticsearch.md'
    - RabbitMQ: 'deployments/RabbitMQ.md' # move this since its not k8s
    - Unleash: 'deployments/unleash.md'
    - Grouper: 'deployments/grouper.md'
    - iRODS CSI Driver: 'deployments/irods-csi-driver.md'
    - Local Exim: 'deployments/local-exim.md'
    - Discovery Environment: 'deployments/DiscoveryEnvironment.md'
    - VICE: 'deployments/vice.md'
    - Jaeger: 'deployments/jaeger.md'

  - Databases:
    - Databases: 'database/main.md'
    - DE Database: 'database/de-db.md'
    - Metadata Database: 'database/metadata-db.md'
    - KeyCloak Database: 'database/keycloak-db.md'
    - Notifications Database: 'database/notifications-db.md'
    - Unleash Database: 'database/unleash-db.md'
    - Grouper Database: 'database/grouper-db.md'
    - QMS Database: 'database/qms-db.md'
    - Portal Database: 'database/portal-db.md'

# Customization
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/
    - icon: fontawesome/brands/github
      link: https://github.com/cyverse/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyverseorg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cyverse.org
    - icon: fontawesome/brands/docker
      link: https://harbor.cyverse.org/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/CyverseOrgProject
  analytics:
    provider: google
    property: G-6WMK2Y07YW

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css