docs_dir: docs/
site_name: CyVerse Core Software Documentation
site_url: https://cyverse.github.io/docs
site_description: CyVerse USA Documentation
site_author: 'CyVerse USA'

# uncomment to show the github icon in the header with
# number of forks & stars
repo_url: https://github.com/cyverse/docs
edit_uri: edit/main/docs

# Copyright
copyright: 'Copyright &copy; 2016-2023 CyVerse'

# JavaScript for Intercom Widget
extra_javascript:
  - javascripts/intercom.js

# logos
#medunilogo: 'images/logo-meduni-graz.png'
#unigrazlogo: 'images/universitaet_graz_logo_signet.png'
#tugrazlogo: 'images/TUG.png'
imgwidth: 70px;
theme:
  highlightjs: true
  name: material
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'assets/de/cyverse_ball_2022.png'
  favicon: 'images/favicon.ico'
# setting features for the navigation tab
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
  # Default values, taken from mkdocs_theme.yml
  language: en
  # custom_dir: 'overrides'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: white)"
      primary: 'white'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

# Navigation Pane

nav:
  - About: 'index.md'
  - DevOps:
    - Getting Started: 'services/getting_started.md'
    - System Overview: 'services/system_overview.md'
    - Subscriptions: 'services/subscriptions.md'
    - API (Terrain): 
      - Overview: 'services/api_overview.md'
      - Endpoints:
        - Overview: 'services/api/endpoints/endpoints.md'
        - App Metadata: 'services/api/endpoints/app-metadata.md'
        - Callbacks: 'services/api/endpoints/callbacks.md'
        - Collaborator List Management: 'services/api/endpoints/collaborator-lists.md'
        - Comments: 'services/api/endpoints/comments.md'
        - Data Search: 'services/api/endpoints/filesystem/search.md'
        - Favorites: 'services/api/endpoints/favorites.md'
        - Notification: 'services/api/endpoints/notifications.md'
        - Ontology Hierarchies: 'services/api/endpoints/app-ontologies.md'
        - Permanent ID Requests: 'services/api/endpoints/permanent-id-requests.md'
        - Quick Launches: 'services/api/endpoints/quick-launches.md'
        - Miscellaneous: 'services/api/endpoints/misc.md'
      - Endpoints Index: 'services/api/endpoint-index.md'
      - Errors: 'services/api/errors.md'
    - Products & Services:
      - Overview: 'services/services_overview.md'
      - Authentication: 'services/keycloak.md'
      - BisQue: [services/bisque.md]
      - Cloud Services: "services/cloud.md"
      - Data Publishing: 'services/dc.md'
      - Data Storage: 'services/ds.md'
      - Discovery Environment: 'services/de.md'
      - DNA Subway: 'services/dnasubway.md'
    - Deployments:
      - Overview: 'deployments/deployment_overview.md'
      - Kubernetes (K8s): 'deployments/kubernetes-deploy.md'
      - User Portal: 'deployments/userportal.md'
      - OpenEBS: 'deployments/openebs.md'
      - KeyCloak: 'deployments/keycloak.md'
      - Mail: 'deployments/exim4.md'
      - Redis HA: 'deployments/redis-ha.md'
      - K8s Resources: 'deployments/k8s-resources.md'
      - K8s Name Spaces: 'deployments/k8s-namespace.md'
      - ElasticSearch: 'deployments/elasticsearch.md'
      - RabbitMQ: 'deployments/RabbitMQ.md' # move this since its not k8s
      - Unleash: 'deployments/unleash.md'
      - Grouper: 'deployments/grouper.md'
      - iRODS CSI Driver: 'deployments/irods-csi-driver.md'
      - Local Exim: 'deployments/local-exim.md'
      - Discovery Environment: 'deployments/DiscoveryEnvironment.md'
      - VICE: 'deployments/vice.md'
      - Jaeger: 'deployments/jaeger.md'
    - Databases:
      - Overview: 'database/main.md'
      - DE: 'database/de-db.md'
      - Metadata: 'database/metadata-db.md'
      - KeyCloak: 'database/keycloak-db.md'
      - Notifications: 'database/notifications-db.md'
      - Unleash: 'database/unleash-db.md'
      - Grouper: 'database/grouper-db.md'
      - QMS: 'database/qms-db.md'
      - Portal: 'database/portal-db.md'
  - Admin Guides:
    - DevOps: 'guides/devops.md'
    - Discovery Environment: 'guides/de.md'
    - Data Store: 'guides/ds.md'
    - User Portal: 'guides/user_portal.md'    
    - Frequently Asked Questions: 'guides/faq.md'

# Customization
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/
    - icon: fontawesome/brands/github
      link: https://github.com/cyverse/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyverseorg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cyverse.org
    - icon: fontawesome/brands/docker
      link: https://harbor.cyverse.org/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/CyverseOrgProject
  analytics:
    provider: google
    property: G-6WMK2Y07YW

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css